In [1]:
path = "Prediction_FileFromDB/InputFile.csv"

In [64]:
import pandas as pd
import numpy as pn

In [3]:
df = pd.read_csv(path)
df.head(5)

,Wafer,Sensor - 1,Sensor - 2,Sensor - 3,Sensor - 4,Sensor - 5,Sensor - 6,Sensor - 7,Sensor - 8,Sensor - 9,...,Sensor - 581,Sensor - 582,Sensor - 583,Sensor - 584,Sensor - 585,Sensor - 586,Sensor - 587,Sensor - 588,Sensor - 589,Sensor - 590
0,1201,3045.98,2544.85,2253.3444,1873.8678,1.1691,100.0,94.9722,0.1210,1.4752,...,NaN,NaN,0.4948,0.0123,0.0033,2.4804,0.0291,0.0102,0.0033,35.0279
1,1202,3151.98,2563.75,2175.2556,1022.1660,1.2833,100.0,100.6222,0.1250,1.4536,...,NaN,NaN,0.5063,0.0113,0.0031,2.2284,0.0291,0.0102,0.0033,35.0279
2,1203,3071.18,2489.86,2195.3000,1151.8233,0.9220,100.0,103.5467,0.1232,1.4826,...,NaN,NaN,0.5033,0.0112,0.0029,2.2320,0.0291,0.0102,0.0033,35.0279
3,1204,2958.46,2523.78,2171.8556,1156.6018,1.4025,100.0,100.1367,0.1243,1.4645,...,NaN,NaN,0.4954,0.0136,0.0033,2.7511,0.0291,0.0102,0.0033,35.0279
4,1205,3196.21,2413.39,2255.5222,1763.0739,1.2226,100.0,101.5878,0.1200,1.4845,...,0.0057,353.8319,0.5058,0.0094,0.0026,1.8673,0.0053,0.0188,0.0057,353.8319

In [4]:
df.shape

(100, 591)

In [65]:
train_path = "Training_FileFromDB/InputFile.csv"

In [66]:
train_df = pd.read_csv(train_path)

In [67]:
train_df.shape

(6696, 592)

In [68]:
train_df.shape

(6696, 592)

In [69]:
train_df.head()

,Wafer,Sensor - 1,Sensor - 2,Sensor - 3,Sensor - 4,Sensor - 5,Sensor - 6,Sensor - 7,Sensor - 8,Sensor - 9,...,Sensor - 582,Sensor - 583,Sensor - 584,Sensor - 585,Sensor - 586,Sensor - 587,Sensor - 588,Sensor - 589,Sensor - 590,Output
0,1201,3045.98,2544.85,2253.3444,1873.8678,1.1691,100.0,94.9722,0.1210,1.4752,...,NaN,0.4948,0.0123,0.0033,2.4804,0.0291,0.0102,0.0033,35.0279,-1
1,1202,3151.98,2563.75,2175.2556,1022.1660,1.2833,100.0,100.6222,0.1250,1.4536,...,NaN,0.5063,0.0113,0.0031,2.2284,0.0291,0.0102,0.0033,35.0279,-1
2,1203,3071.18,2489.86,2195.3000,1151.8233,0.9220,100.0,103.5467,0.1232,1.4826,...,NaN,0.5033,0.0112,0.0029,2.2320,0.0291,0.0102,0.0033,35.0279,-1
3,1204,2958.46,2523.78,2171.8556,1156.6018,1.4025,100.0,100.1367,0.1243,1.4645,...,NaN,0.4954,0.0136,0.0033,2.7511,0.0291,0.0102,0.0033,35.0279,-1
4,1205,3196.21,2413.39,2255.5222,1763.0739,1.2226,100.0,101.5878,0.1200,1.4845,...,353.8319,0.5058,0.0094,0.0026,1.8673,0.0053,0.0188,0.0057,353.8319,-1

In [70]:
from file_operations import file_methods
from data_preprocessing import preprocessing
from data_ingestion import data_loader_prediction
from application_logging import logger
from Prediction_Raw_Data_Validation.predictionDataValidation import Prediction_Data_validation

In [6]:
k_model = "models/KMeans/KMeans.sav"

In [71]:
from sklearn.preprocessing import StandardScaler
from sklearn.impute import KNNImputer
import numpy as np
import pandas as pd
from sklearn import decomposition
import matplotlib.pyplot as plt
def impute(data):
    imputer=KNNImputer(n_neighbors=3, weights='uniform',missing_values=np.nan)
    new_array=imputer.fit_transform(data) # impute the missing values
    # convert the nd-array returned in the step above to a Dataframe
    new_data=pd.DataFrame(data=new_array, columns=data.columns)
    return new_data

In [72]:
df = impute(train_df)

In [73]:
df.head()

,Wafer,Sensor - 1,Sensor - 2,Sensor - 3,Sensor - 4,Sensor - 5,Sensor - 6,Sensor - 7,Sensor - 8,Sensor - 9,...,Sensor - 582,Sensor - 583,Sensor - 584,Sensor - 585,Sensor - 586,Sensor - 587,Sensor - 588,Sensor - 589,Sensor - 590,Output
0,1201.0,3045.98,2544.85,2253.3444,1873.8678,1.1691,100.0,94.9722,0.1210,1.4752,...,78.6294,0.4948,0.0123,0.0033,2.4804,0.0291,0.0102,0.0033,35.0279,-1.0
1,1202.0,3151.98,2563.75,2175.2556,1022.1660,1.2833,100.0,100.6222,0.1250,1.4536,...,262.6164,0.5063,0.0113,0.0031,2.2284,0.0291,0.0102,0.0033,35.0279,-1.0
2,1203.0,3071.18,2489.86,2195.3000,1151.8233,0.9220,100.0,103.5467,0.1232,1.4826,...,54.1279,0.5033,0.0112,0.0029,2.2320,0.0291,0.0102,0.0033,35.0279,-1.0
3,1204.0,2958.46,2523.78,2171.8556,1156.6018,1.4025,100.0,100.1367,0.1243,1.4645,...,27.7705,0.4954,0.0136,0.0033,2.7511,0.0291,0.0102,0.0033,35.0279,-1.0
4,1205.0,3196.21,2413.39,2255.5222,1763.0739,1.2226,100.0,101.5878,0.1200,1.4845,...,353.8319,0.5058,0.0094,0.0026,1.8673,0.0053,0.0188,0.0057,353.8319,-1.0

In [74]:
df.drop("Wafer", axis="columns", inplace=True)

In [75]:
df.head()

,Sensor - 1,Sensor - 2,Sensor - 3,Sensor - 4,Sensor - 5,Sensor - 6,Sensor - 7,Sensor - 8,Sensor - 9,Sensor - 10,...,Sensor - 582,Sensor - 583,Sensor - 584,Sensor - 585,Sensor - 586,Sensor - 587,Sensor - 588,Sensor - 589,Sensor - 590,Output
0,3045.98,2544.85,2253.3444,1873.8678,1.1691,100.0,94.9722,0.1210,1.4752,0.0084,...,78.6294,0.4948,0.0123,0.0033,2.4804,0.0291,0.0102,0.0033,35.0279,-1.0
1,3151.98,2563.75,2175.2556,1022.1660,1.2833,100.0,100.6222,0.1250,1.4536,-0.0110,...,262.6164,0.5063,0.0113,0.0031,2.2284,0.0291,0.0102,0.0033,35.0279,-1.0
2,3071.18,2489.86,2195.3000,1151.8233,0.9220,100.0,103.5467,0.1232,1.4826,0.0136,...,54.1279,0.5033,0.0112,0.0029,2.2320,0.0291,0.0102,0.0033,35.0279,-1.0
3,2958.46,2523.78,2171.8556,1156.6018,1.4025,100.0,100.1367,0.1243,1.4645,0.0001,...,27.7705,0.4954,0.0136,0.0033,2.7511,0.0291,0.0102,0.0033,35.0279,-1.0
4,3196.21,2413.39,2255.5222,1763.0739,1.2226,100.0,101.5878,0.1200,1.4845,-0.0037,...,353.8319,0.5058,0.0094,0.0026,1.8673,0.0053,0.0188,0.0057,353.8319,-1.0

In [76]:
Output = df["Output"]

In [77]:
df.drop("Output", axis="columns", inplace=True)

In [78]:
df.head()

,Sensor - 1,Sensor - 2,Sensor - 3,Sensor - 4,Sensor - 5,Sensor - 6,Sensor - 7,Sensor - 8,Sensor - 9,Sensor - 10,...,Sensor - 581,Sensor - 582,Sensor - 583,Sensor - 584,Sensor - 585,Sensor - 586,Sensor - 587,Sensor - 588,Sensor - 589,Sensor - 590
0,3045.98,2544.85,2253.3444,1873.8678,1.1691,100.0,94.9722,0.1210,1.4752,0.0084,...,0.0071,78.6294,0.4948,0.0123,0.0033,2.4804,0.0291,0.0102,0.0033,35.0279
1,3151.98,2563.75,2175.2556,1022.1660,1.2833,100.0,100.6222,0.1250,1.4536,-0.0110,...,0.0165,262.6164,0.5063,0.0113,0.0031,2.2284,0.0291,0.0102,0.0033,35.0279
2,3071.18,2489.86,2195.3000,1151.8233,0.9220,100.0,103.5467,0.1232,1.4826,0.0136,...,0.0032,54.1279,0.5033,0.0112,0.0029,2.2320,0.0291,0.0102,0.0033,35.0279
3,2958.46,2523.78,2171.8556,1156.6018,1.4025,100.0,100.1367,0.1243,1.4645,0.0001,...,0.0020,27.7705,0.4954,0.0136,0.0033,2.7511,0.0291,0.0102,0.0033,35.0279
4,3196.21,2413.39,2255.5222,1763.0739,1.2226,100.0,101.5878,0.1200,1.4845,-0.0037,...,0.0057,353.8319,0.5058,0.0094,0.0026,1.8673,0.0053,0.0188,0.0057,353.8319

In [80]:
from sklearn.preprocessing import StandardScaler
scaler = StandardScaler()
standardized_data = scaler.fit_transform(df)

In [81]:
scaler

StandardScaler(copy=True, with_mean=True, with_std=True)

In [83]:
import os
from sklearn.externals import joblib
path="scaler/scaler.save"
if os.path.exists(path):
    os.remove(path)
joblib.dump(scaler, path)
standardized_data = pd.DataFrame(standardized_data)

In [36]:
X.shape

(6696, 590)

In [38]:
X = pd.DataFrame(X)

In [39]:
X.head()

,0,1,2,3,4,5,6,7,8,9,...,580,581,582,583,584,585,586,587,588,589
0,0.311533,0.686086,1.697122,0.741548,-0.072261,0.0,-0.636277,-0.007607,0.332719,0.557306,...,0.521350,-0.226991,-1.581698,-0.166817,-0.130635,-0.155417,0.450143,-0.630063,-0.595055,-0.631554
1,1.632304,0.950625,-0.813928,-0.847331,-0.070771,0.0,0.093237,0.289590,0.059887,-0.757922,...,3.326052,1.797633,1.950290,-0.227418,-0.186508,-0.228579,0.450143,-0.630063,-0.595055,-0.631554
2,0.625528,-0.083596,-0.169373,-0.605451,-0.075485,0.0,0.470841,0.155851,0.426189,0.909842,...,-0.642303,-0.496610,1.028902,-0.233478,-0.242380,-0.227534,0.450143,-0.630063,-0.595055,-0.631554
3,-0.778976,0.391174,-0.923259,-0.596536,-0.069216,0.0,0.030550,0.237581,0.197566,-0.005394,...,-1.000350,-0.786652,-1.397420,-0.088035,-0.130635,-0.076826,0.450143,-0.630063,-0.595055,-0.631554
4,2.183415,-1.153929,1.767152,0.534858,-0.071563,0.0,0.217913,-0.081907,0.450188,-0.263017,...,0.103628,2.801384,1.796725,-0.342560,-0.326188,-0.333415,-1.327777,0.316946,0.189345,2.940506

In [41]:
X[5].value_counts()

0.0    6696
Name: 5, dtype: int64

In [43]:
X.shape

(6696, 590)

In [9]:
import pickle

In [10]:
with open(k_model,'rb') as f:
    model = pickle.load(f)

In [42]:
test_path = "Prediction_FileFromDB/InputFile.csv"

In [43]:
df = pd.read_csv(test_path)
df.shape

(100, 591)

In [34]:
from file_operations import file_methods
from data_preprocessing import preprocessing
from data_ingestion import data_loader_prediction
from application_logging import logger
from Prediction_Raw_Data_Validation.predictionDataValidation import Prediction_Data_validation

def preprocess(data):
    log_writer = logger.App_Logger()
#     self.pred_data_val.deletePredictionFile() #deletes the existing prediction file from last run!
#     data_getter=data_loader_prediction.Data_Getter_Pred(self.file_object,self.log_writer)
#     data=data_getter.get_data()

    #code change
    # wafer_names=data['Wafer']
    # data=data.drop(labels=['Wafer'],axis=1)

    preprocessor=preprocessing.Preprocessor("edf","T.txt", log_writer)
    is_null_present=preprocessor.is_null_present("ses",data)
    if(is_null_present):
        data=preprocessor.impute_missing_values("sfd",data)
        
    #data=data.to_numpy()
#     file_loader=file_methods.File_Operation(self.file_object,self.log_writer)
#     kmeans=file_loader.load_model('KMeans')

#     ##Code changed
#     #pred_data = data.drop(['Wafer'],axis=1)
#     print(data.shape)
#     print(data.head())
    return data
#     clusters=kmeans.predict(data.drop(['Wafer'],axis=1))#drops the first column for cluster prediction

In [47]:
from sklearn.impute import KNNImputer
import numpy as np
def impute(data):
    imputer=KNNImputer(n_neighbors=3, weights='uniform',missing_values=np.nan)
    new_array=imputer.fit_transform(data) # impute the missing values
    # convert the nd-array returned in the step above to a Dataframe
    new_data=pd.DataFrame(data=new_array, columns=data.columns)
    return new_data

In [48]:
df.shape

(100, 591)

In [49]:
df = impute(df)

In [50]:
r = model.predict(df)

ValueError: Incorrect number of features. Got 591 features, expected 474

In [54]:
df.head()

,Sensor - 1,Sensor - 2,Sensor - 3,Sensor - 4,Sensor - 5,Sensor - 6,Sensor - 7,Sensor - 8,Sensor - 9,Sensor - 10,...,Sensor - 581,Sensor - 582,Sensor - 583,Sensor - 584,Sensor - 585,Sensor - 586,Sensor - 587,Sensor - 588,Sensor - 589,Sensor - 590
0,3045.98,2544.85,2253.3444,1873.8678,1.1691,100.0,94.9722,0.1210,1.4752,0.0084,...,0.003700,47.306533,0.4948,0.0123,0.0033,2.4804,0.0291,0.0102,0.0033,35.0279
1,3151.98,2563.75,2175.2556,1022.1660,1.2833,100.0,100.6222,0.1250,1.4536,-0.0110,...,0.004067,85.497400,0.5063,0.0113,0.0031,2.2284,0.0291,0.0102,0.0033,35.0279
2,3071.18,2489.86,2195.3000,1151.8233,0.9220,100.0,103.5467,0.1232,1.4826,0.0136,...,0.005933,67.947167,0.5033,0.0112,0.0029,2.2320,0.0291,0.0102,0.0033,35.0279
3,2958.46,2523.78,2171.8556,1156.6018,1.4025,100.0,100.1367,0.1243,1.4645,0.0001,...,0.003633,153.424467,0.4954,0.0136,0.0033,2.7511,0.0291,0.0102,0.0033,35.0279
4,3196.21,2413.39,2255.5222,1763.0739,1.2226,100.0,101.5878,0.1200,1.4845,-0.0037,...,0.005700,353.831900,0.5058,0.0094,0.0026,1.8673,0.0053,0.0188,0.0057,353.8319

In [53]:
df = df.drop("Wafer", axis="columns")

In [60]:
df.shape

(100, 590)

### PCA

In [61]:
# std
from sklearn.preprocessing import StandardScaler
standardized_data = StandardScaler().fit_transform(df)
print(standardized_data.shape)

(100, 590)

In [72]:
from sklearn import decomposition
pca = decomposition.PCA(0.95)
import matplotlib.pyplot as plt

In [67]:
df = standardized_data

In [73]:
pca_data = pca.fit_transform(df)

In [74]:
pca_data.shape

(100, 72)

In [71]:
df.shape[1] - pca_data.shape[1]

531

### PCA for train